-- Migration 009: automation_jobs table for tracking queued n8n webhook executions
CREATE TABLE IF NOT EXISTS automation_jobs (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workflow_key       TEXT NOT NULL,
  workflow_version   INT NOT NULL DEFAULT 1,
  status             TEXT NOT NULL CHECK (status IN ('queued', 'processing', 'completed', 'failed', 'dead_letter')),
  payload            JSONB NOT NULL,
  triggered_by_event TEXT,
  attempt_count      INT NOT NULL DEFAULT 0,
  last_error         TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_automation_jobs_status ON automation_jobs(status);
CREATE INDEX IF NOT EXISTS idx_automation_jobs_created_at ON automation_jobs(created_at DESC);

-- Widen activity_log CHECK constraints to allow automation entity_type and action types.
-- Drop old constraints (names auto-generated by Postgres use the pattern <table>_<column>_check).
ALTER TABLE activity_log DROP CONSTRAINT IF EXISTS activity_log_entity_type_check;
ALTER TABLE activity_log ADD CONSTRAINT activity_log_entity_type_check
  CHECK (entity_type IN ('lead', 'note', 'meeting', 'followup', 'user', 'automation'));

ALTER TABLE activity_log DROP CONSTRAINT IF EXISTS activity_log_action_check;
ALTER TABLE activity_log ADD CONSTRAINT activity_log_action_check
  CHECK (action IN ('create', 'update', 'delete', 'status_change', 'automation_trigger', 'automation_complete', 'automation_fail'));
